spring:
  application:
    name: start
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  docker:
    compose:
      enabled: true
      file: compose.yml
      lifecycle-management: start_and_stop
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-5.6-luna
          reasoning-effort: none

    vectorstore:
      pgvector:
        initialize-schema: true
