spring:
  application:
    name: openapi-worker
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  docker:
    compose:
      enabled: true
      file: compose.yml
      lifecycle-management: start_and_stop
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-5.6-luna
          reasoning-effort: none
    mcp:
      client:
        enabled: true
        name: playwright-client
        request-timeout: 60s
#        type: SYNC
        toolcallback:
          enabled: true
        stdio:
          connections:
            playwright:
              command: cmd.exe
              args:
                - "/c"
                - "npx"
                - "-y"
#                - "@angiejones/mcp-selenium"
                - "@playwright/mcp@latest"

    vectorstore:
      pgvector:
        initialize-schema: true

management:
  endpoints.web.exposure.include: health,info,prometheus
