spring:
  application:
    name: openapi-worker
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  docker:
    compose:
      enabled: true
      file: compose.yml
      lifecycle-management: start_only
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-5.6-luna
          reasoning-effort: none

    mcp:
      client:
        enabled: true
        name: playwright-client
        request-timeout: 60s
        #        type: SYNC
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:servers/mcp-servers.json
        sse:
          connections:
            weather:
              url: http://localhost:8090
              sse-endpoint: /sse

    vectorstore:
      pgvector:
        initialize-schema: true

management:
  endpoints.web.exposure.include: health,info,prometheus

model:
  chat:
    options:
      temperature: 1.0

vector-store:
  top-k: 5
  similarity-threshold: 0.7


#logging:
#  level:
#    # Логирование логики памяти Spring AI и Redis-репозитория
#    org.springframework.ai.chat.memory: DEBUG
#    org.springframework.ai.chat.memory.repository.redis: TRACE
#
#    # Если используется Jedis (стандарт для RedisChatMemoryRepository)
#    redis.clients.jedis: DEBUG